<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Click me</name>
   <tag></tag>
   <elementGuidId>68e42471-7195-4868-9ae0-1d39ea5c7d4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b50d4410-4b1d-448b-92ce-e4bb092b1579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dcd1a1ba-5a11-4c61-830b-ecc296450ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click me!</value>
      <webElementGuid>b8c164b6-81b5-4102-a4f7-4882dec23869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button&quot;)</value>
      <webElementGuid>58639bd6-9fd1-4967-a983-7c60cbd9c7a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button']</value>
      <webElementGuid>0ebf22d8-49fe-4840-83bf-e00eee18e510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Your Name :'])[1]/following::button[1]</value>
      <webElementGuid>d2114d31-2018-42a8-a087-9640c3b093be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HH:MM:SS.sss'])[2]/following::button[1]</value>
      <webElementGuid>39c2fae1-4fa9-4ae4-adf9-c7576fae4c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'button', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>6ba779ae-7e5a-41c3-840a-17afc0c26156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click me!']/parent::*</value>
      <webElementGuid>50d57523-8dc0-4d8b-9d2e-66cd7aefd3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>96d310b0-f493-4584-9edb-87a04e60f17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button' and (text() = 'Click me!' or . = 'Click me!')]</value>
      <webElementGuid>949cb66d-31f6-4414-ae58-626884391f14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
