<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Next</name>
   <tag></tag>
   <elementGuidId>885bfcaf-5081-4193-9059-376318579337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.w3-clear.nextprev > a.w3-right.w3-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9e5572eb-6554-4c76-939e-eb5c3228fbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-right w3-btn</value>
      <webElementGuid>6896452d-dab9-4172-9517-3e50484d5f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mysql_select.asp</value>
      <webElementGuid>348ec578-de2d-487e-b3f2-eac03ec4b555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next ❯</value>
      <webElementGuid>f838a421-166c-4230-adb1-f46a37e0d612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;w3-clear nextprev&quot;]/a[@class=&quot;w3-right w3-btn&quot;]</value>
      <webElementGuid>deb9277d-895e-46c6-b484-c6ffe2266ee5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/a[2]</value>
      <webElementGuid>4bc6a689-803b-494c-aa3d-af67dd61db4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Next ❯')]</value>
      <webElementGuid>db52c6fe-c03c-4922-9981-e94dbf39e9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='❮ Previous'])[1]/following::a[1]</value>
      <webElementGuid>290732b1-32a5-407b-be49-7d3dff239678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQL'])[4]/following::a[2]</value>
      <webElementGuid>c9244247-9342-4d50-99b1-a1f13170c5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is SQL?'])[1]/preceding::a[1]</value>
      <webElementGuid>2258d704-c9b3-4748-a38f-5fab52a98b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How to Use SQL'])[1]/preceding::a[1]</value>
      <webElementGuid>06893713-5982-4ff6-b676-67f905c34571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next ❯']/parent::*</value>
      <webElementGuid>ed6d0036-2009-4f75-a90a-be9ff3a0aa84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'mysql_select.asp')])[2]</value>
      <webElementGuid>08ee96b5-8209-4c0d-831a-9e713665fc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/a[2]</value>
      <webElementGuid>964973d6-04ab-4384-bd81-d25d30281515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mysql_select.asp' and (text() = 'Next ❯' or . = 'Next ❯')]</value>
      <webElementGuid>12b92651-c006-4cfc-a79a-2b96cb84f616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
