<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Excercises filter input_filter-exerci_ee1ae2</name>
   <tag></tag>
   <elementGuidId>cf6ae281-605e-4bdf-bd1b-ef4885d5004f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-exercises-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-exercises-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bb1fe5a-f6a3-4432-9c7f-417aab7ff3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-exercises-input</value>
      <webElementGuid>cb47ca39-36c4-4619-9c4e-9fce52770aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.filter(event, 'nav_exercises')</value>
      <webElementGuid>76d3f593-6db0-42f5-8273-15338f80fe59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56052516-fe06-4e6e-a4db-6e2cc86ccdf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-input</value>
      <webElementGuid>6af8e1d2-2fcb-444a-bd96-3a863c1a031d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter...</value>
      <webElementGuid>1e693552-0ab7-498c-819b-3be2481bc7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Exercises filter bar</value>
      <webElementGuid>913b3b27-169f-46fa-87b4-7c7cb6be3a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-exercises-input&quot;)</value>
      <webElementGuid>f0dc0b77-45e3-4b83-a22d-3da76299c1d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-exercises-input']</value>
      <webElementGuid>12018ce1-e237-419e-93ec-3ab534c3a25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exercises_list']/div/div[2]/div/input</value>
      <webElementGuid>e58ea24e-31a2-475b-9321-f8c749170d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>e19613ed-0cbe-49d2-9afd-717ce86696bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-exercises-input' and @type = 'text' and @placeholder = 'Filter...']</value>
      <webElementGuid>09ecc91c-8232-4949-83d1-0b834084f785</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
