<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Excercises filter input_filter-exerci_ee1ae2</name>
   <tag></tag>
   <elementGuidId>8c1ef717-34fe-4e74-99f2-fa2453211c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-exercises-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-exercises-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bff4d58a-0f3b-4ee8-a0b0-66b1bce6382a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-exercises-input</value>
      <webElementGuid>28b5598c-b502-4936-b8bb-8f91c24b738a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.filter(event, 'nav_exercises')</value>
      <webElementGuid>ac152edb-ab3e-4773-9990-e49995b4e1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e755443-8624-4ea0-aa41-187ac43cb998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-input</value>
      <webElementGuid>5bb72488-d8b2-4f45-a49e-dfcc55b07730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter...</value>
      <webElementGuid>c16a7497-76af-45ae-bec2-750a1bdaf412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Exercises filter bar</value>
      <webElementGuid>893620e9-5919-4a5c-ba42-d5c2908c0708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-exercises-input&quot;)</value>
      <webElementGuid>0ac2e374-4d32-46fb-bfd8-8eb0f2c21f77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-exercises-input']</value>
      <webElementGuid>bae55b89-5bc9-4a88-9979-4fec700012b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exercises_list']/div/div[2]/div/input</value>
      <webElementGuid>ceea10a9-37d9-42a4-bc05-6669fa1ca518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>013dbb7b-a698-4621-801a-be5a37c9d57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-exercises-input' and @type = 'text' and @placeholder = 'Filter...']</value>
      <webElementGuid>fecf0a94-6f9e-4a48-ac6e-45641aad00f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
