<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter field for certifications_filte_73e64a</name>
   <tag></tag>
   <elementGuidId>03ab65d2-5d28-414f-8364-42ae25a2294b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-certified-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-certified-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7dd2286-fa37-4876-b33d-cec0ed64002c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-certified-input</value>
      <webElementGuid>f9cd372e-5dfe-42c7-9714-086acedeb3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.filter(event, 'nav_certified')</value>
      <webElementGuid>e64d6b94-38dc-4675-af44-23ca7127667b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8787cf5d-9421-4608-b159-29a329dbf77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-input</value>
      <webElementGuid>463ba39b-4ac4-4707-bfa2-cf6ee43ea060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter...</value>
      <webElementGuid>7aca5329-e47b-42f8-98ba-32e78b2eab47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Certificate filter bar</value>
      <webElementGuid>c7b60191-40e7-4c57-8a1c-e6886328ace5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-certified-input&quot;)</value>
      <webElementGuid>8665682b-75e0-47b4-a68b-e2789eb637b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-certified-input']</value>
      <webElementGuid>3740a799-591a-4a85-8967-97b204fce7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='certified_list']/div/div[2]/div/input</value>
      <webElementGuid>7ad9b9db-da48-41a2-88f5-39355aa3808f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>f6843ab2-3811-4650-bf31-933ff7fec962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-certified-input' and @type = 'text' and @placeholder = 'Filter...']</value>
      <webElementGuid>a29c4c30-9509-4c23-9e14-e6da7527c49d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
