<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__topnav-icons fa fa-menu w3-hide-large w3_c63883</name>
   <tag></tag>
   <elementGuidId>f6ecbf0b-f009-48fc-adca-a5077334308c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.topnav-icons.fa.fa-menu.w3-hide-large.w3-left.w3-bar-item.w3-button.ga-nav</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='open_menu()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f3934b29-a2a6-4e13-a7f4-c7798e391fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>8bf8bfe3-f1db-46a4-9774-67d03e2a9062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>topnav-icons fa fa-menu w3-hide-large w3-left w3-bar-item w3-button ga-nav</value>
      <webElementGuid>9fdbf053-2267-4ba1-ad39-022f19ec5aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>open_menu()</value>
      <webElementGuid>b0c0c14d-8120-407e-9d71-fc58e74c1a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>09c33e6f-0ae2-408c-8734-cb4e8af724c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menubtn_container&quot;)/span[1]/a[@class=&quot;topnav-icons fa fa-menu w3-hide-large w3-left w3-bar-item w3-button ga-nav&quot;]</value>
      <webElementGuid>1601a21a-0aff-4ba7-b38e-c266750ab18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_W3Schools Tryit Editor/iframe</value>
      <webElementGuid>aef9a537-b00f-4131-adce-0d3d788aedc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='open_menu()']</value>
      <webElementGuid>1cb48093-df6f-4101-9a0a-e84a1a8b6a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menubtn_container']/span/a</value>
      <webElementGuid>09f9e459-6cdb-42c8-8d6d-4c69bcab38cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[2]</value>
      <webElementGuid>540919ba-bc13-4f33-a644-4fc1192f6791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>278312e2-2fdf-4ac5-93c3-803453876517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @title = 'Menu']</value>
      <webElementGuid>c3314ed3-e4cf-4b32-9694-0751a2f3d03b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
