<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_JAVASCRIPT</name>
   <tag></tag>
   <elementGuidId>d6ea4e33-80db-439c-b8e4-0ddcba7d5eb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subtopnav']/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df20373a-2ec1-4964-97d9-7e6780145ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/js/default.asp</value>
      <webElementGuid>7716643d-eb7a-4a2d-8de9-cab6f1dcac45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ga-nav</value>
      <webElementGuid>84ee4bbb-ee39-43f9-bad8-9f9059c0482e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>JavaScript Tutorial</value>
      <webElementGuid>f0c01252-dfbd-488f-9b51-2f6c733c017b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JAVASCRIPT</value>
      <webElementGuid>1d3ee616-21ad-46aa-8c6f-a3267a65bb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subtopnav&quot;)/a[@class=&quot;ga-nav&quot;]</value>
      <webElementGuid>cf7b866e-6226-4447-97a2-921eb9319cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_W3Schools Tryit Editor/iframe</value>
      <webElementGuid>3e2ad102-cf2e-475f-980c-935c171c33f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subtopnav']/a[3]</value>
      <webElementGuid>4ebaf69e-2315-43c0-9fa7-a1ae646a55b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'JAVASCRIPT')]</value>
      <webElementGuid>1cd606dc-1390-4eea-9e4e-5206ec9ef5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSS'])[3]/following::a[1]</value>
      <webElementGuid>24733a9b-da40-49dd-bd29-7b212b20a4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML'])[3]/following::a[2]</value>
      <webElementGuid>c25d01cf-3291-42cd-8dc2-5f444e87a538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQL'])[3]/preceding::a[1]</value>
      <webElementGuid>adf299f6-404b-420a-9a95-25d9d96ab839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PYTHON'])[1]/preceding::a[2]</value>
      <webElementGuid>0aa478bc-90a3-4d9e-bd20-0833abbe0a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JAVASCRIPT']/parent::*</value>
      <webElementGuid>7f19f50d-5d03-40f8-b093-c95d659e1f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/js/default.asp')])[3]</value>
      <webElementGuid>3d3d5f0a-3693-4290-962a-8d94215dd676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a[3]</value>
      <webElementGuid>6c29f481-1c53-4243-aa7c-617fd11e5bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/js/default.asp' and @title = 'JavaScript Tutorial' and (text() = 'JAVASCRIPT' or . = 'JAVASCRIPT')]</value>
      <webElementGuid>578e616d-0255-42a8-add3-494e45ee2eb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
