<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Excercises filter input_filter-exerci_ee1ae2</name>
   <tag></tag>
   <elementGuidId>f61a5721-0927-4224-91fb-a895e3d2ef6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-exercises-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-exercises-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d26b6d1a-69e0-4d35-a46f-e13acd9b2faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-exercises-input</value>
      <webElementGuid>5d133561-2d50-43b8-ba69-76977bd4ca31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.filter(event, 'nav_exercises')</value>
      <webElementGuid>00f117de-402e-4047-b04a-695d1dd9a13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e706c7f0-f852-403a-a4fa-4cc5c142f042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-input</value>
      <webElementGuid>1e831cce-4034-4e66-9b98-b590ff28dcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter...</value>
      <webElementGuid>2d714599-adda-47e2-8ea7-5743928ccf68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Exercises filter bar</value>
      <webElementGuid>c121be0a-b31a-4224-92fe-c003488dca42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-exercises-input&quot;)</value>
      <webElementGuid>34363349-e2bb-43c4-9c0c-60c248571cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_W3Schools Tryit Editor/iframe</value>
      <webElementGuid>de1b4db3-98ec-4248-9c2c-cc3c3778c69e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-exercises-input']</value>
      <webElementGuid>4897e006-3270-4575-beb3-9b57f154d995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exercises_list']/div/div[2]/div/input</value>
      <webElementGuid>231ff3b8-d62b-4e74-9256-cec821f28fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>1a7fb8b7-b5a5-4a56-84eb-d29383e84d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-exercises-input' and @type = 'text' and @placeholder = 'Filter...']</value>
      <webElementGuid>3342d774-fbad-4f96-ab2f-b3d2d16a9974</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
