<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea</name>
   <tag></tag>
   <elementGuidId>e2d88b4b-7d1d-42f4-b12b-6d177b8052a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.CodeMirror.cm-s-default.CodeMirror-wrap.CodeMirror-focused > div > textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='textareawrapper']/div/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>03035171-14dc-4b72-9c61-9c76e49aaebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5c137b95-f33d-48cd-ac6e-851dfbd4e2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7dd7cb40-da88-4364-b65e-9b2a62449abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5948b7ad-70cd-4d03-8213-500a6f1f89e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7c632ee5-be18-4dc9-b378-5f9035a3700a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textareawrapper&quot;)/div[@class=&quot;CodeMirror cm-s-default CodeMirror-wrap CodeMirror-focused&quot;]/div[1]/textarea[1]</value>
      <webElementGuid>c69e3b03-ff80-4862-b8e2-ad69376c2c20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='textareawrapper']/div/div/textarea</value>
      <webElementGuid>292ee9af-45ca-432c-81ed-7465564c4a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/textarea</value>
      <webElementGuid>a0030ac9-b782-43fd-ab51-4d72727e8394</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
